version: '3'

services:
  # サービス名
  django:
    build:
      context: ./containers    # Dockerfileがあるディレクトリまでの相対パス
      dockerfile: Dockerfile   # Dockerfileのファイル名

    # 使用するポートの設定
    ports:
      - "8000:8000"
    
    # 対話的なセッションやコマンドラインの操作を許可する
    tty: true

    volumes:
      # ローカルの作業ディレクトリと仮想環境の作業ディレクトリの対応づけ
      - ${SRC_PATH}:/root/workspace

    depends_on:
      - db
  
  db:
    platform: linux/x86_64
    image: mysql:5.7.33
    volumes:
      - ./mysql/volume:/var/lib/mysql
      - ./mysql/my.cnf:/etc/my.cnf
    environment:
      MYSQL_DATABASE: django_local
      MYSQL_USER: django_user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      TZ: Asia/Tokyo
    ports:
        - "3306:3306"
    restart: always
